#ifndef NFT_HASHES_HSVHASH_H
#define NFT_HASHES_HSVHASH_H

#include <stdint.h>

/* hsvHash: a direct C port of Buchner's imagehash.colorhash() (binbits=3).
 * The paper's Section II-C(v) prose describes a block/region-based
 * algorithm, but the paper's actual numbers were generated by imagehash,
 * whose only HSV-based function is colorhash() -- a global histogram over
 * black/gray/hue-binned-saturated pixel fractions, not spatial blocks.
 * That's what this ports.
 *
 * 42-bit fingerprint (top 22 bits of the returned uint64_t are always
 * zero): the fraction of near-black pixels, the fraction of near-gray
 * (low-saturation, not already counted as black) pixels, and two 6-bin hue
 * histograms -- one for medium-saturation ("faint") colored pixels, one
 * for high-saturation ("bright") colored pixels -- each of the 14 values
 * quantized to 3 bits via colorhash()'s own (non-monotonic) bit table. */
typedef uint64_t hsvhash_t;

/* Decodes the image at `path`, computes its hsvHash, and writes it to
 * `out_hash`. Returns 0 on success, -1 on bad arguments, -2 if the image
 * could not be decoded. Allocates only to decode the image. */
int hsvhash_from_file(const char *path, hsvhash_t *out_hash);

/* Hamming distance between two hsvHash values. */
int hsvhash_distance(hsvhash_t a, hsvhash_t b);

#endif /* NFT_HASHES_HSVHASH_H */
